<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC5\x01\x0A\x0Ccommon.proto\x12\x0Cproto.common\"0\x0A\x0FMessageResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\x12\x0C\x0A\x04code\x18\x02 \x01(\x05\"%\x0A\x10NetworkInterface\x12\x11\x0A\x09interface\x18\x01 \x01(\x09\"F\x0A\x16ListInterfacesResponse\x12,\x0A\x04data\x18\x01 \x03(\x0B2\x1E.proto.common.NetworkInterfaceb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

