<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shadowsocks.proto

namespace GPBMetadata;

class Shadowsocks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCF\x07\x0A\x11shadowsocks.proto\x12\x11proto.shadowsocks\"\xBE\x01\x0A\x0CMountRequest\x12\x13\x0A\x0Bserver_port\x18\x01 \x01(\x05\x12\x12\x0A\x0Alocal_port\x18\x02 \x01(\x05\x12\x10\x0A\x08password\x18\x03 \x01(\x09\x12\x0E\x0A\x06method\x18\x04 \x01(\x09\x12\x0F\x0A\x07timeout\x18\x05 \x01(\x09\x12\x11\x0A\x09fast_open\x18\x06 \x01(\x08\x12\x10\x0A\x08no_delay\x18\x07 \x01(\x08\x12\x0C\x0A\x04mode\x18\x08 \x01(\x09\x12\x12\x0A\x0Areuse_port\x18\x09 \x01(\x08\x12\x0B\x0A\x03dns\x18\x0A \x01(\x09\"\"\x0A\x0FMessageResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\"\x0E\x0A\x0CEmptyRequest2\xA9\x05\x0A\x12ShadowsocksService\x12L\x0A\x05mount\x12\x1F.proto.shadowsocks.MountRequest\x1A\".proto.shadowsocks.MessageResponse\x12M\x0A\x06delete\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12R\x0A\x0BServerStart\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12S\x0A\x0CServerStatus\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12Q\x0A\x0AServerStop\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12R\x0A\x0BClientStart\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12S\x0A\x0CClientStatus\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponse\x12Q\x0A\x0AClientStop\x12\x1F.proto.shadowsocks.EmptyRequest\x1A\".proto.shadowsocks.MessageResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

