<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shadowsocks.proto

namespace Proto\Shadowsocks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.shadowsocks.MountRequest</code>
 */
class MountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 server_port = 1;</code>
     */
    protected $server_port = 0;
    /**
     * Generated from protobuf field <code>int32 local_port = 2;</code>
     */
    protected $local_port = 0;
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string method = 4;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>string timeout = 5;</code>
     */
    protected $timeout = '';
    /**
     * Generated from protobuf field <code>bool fast_open = 6;</code>
     */
    protected $fast_open = false;
    /**
     * Generated from protobuf field <code>bool no_delay = 7;</code>
     */
    protected $no_delay = false;
    /**
     * Generated from protobuf field <code>string mode = 8;</code>
     */
    protected $mode = '';
    /**
     * Generated from protobuf field <code>bool reuse_port = 9;</code>
     */
    protected $reuse_port = false;
    /**
     * Generated from protobuf field <code>string dns = 10;</code>
     */
    protected $dns = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $server_port
     *     @type int $local_port
     *     @type string $password
     *     @type string $method
     *     @type string $timeout
     *     @type bool $fast_open
     *     @type bool $no_delay
     *     @type string $mode
     *     @type bool $reuse_port
     *     @type string $dns
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shadowsocks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 server_port = 1;</code>
     * @return int
     */
    public function getServerPort()
    {
        return $this->server_port;
    }

    /**
     * Generated from protobuf field <code>int32 server_port = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->server_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 local_port = 2;</code>
     * @return int
     */
    public function getLocalPort()
    {
        return $this->local_port;
    }

    /**
     * Generated from protobuf field <code>int32 local_port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLocalPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->local_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 4;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timeout = 5;</code>
     * @return string
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>string timeout = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fast_open = 6;</code>
     * @return bool
     */
    public function getFastOpen()
    {
        return $this->fast_open;
    }

    /**
     * Generated from protobuf field <code>bool fast_open = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setFastOpen($var)
    {
        GPBUtil::checkBool($var);
        $this->fast_open = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool no_delay = 7;</code>
     * @return bool
     */
    public function getNoDelay()
    {
        return $this->no_delay;
    }

    /**
     * Generated from protobuf field <code>bool no_delay = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoDelay($var)
    {
        GPBUtil::checkBool($var);
        $this->no_delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mode = 8;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>string mode = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reuse_port = 9;</code>
     * @return bool
     */
    public function getReusePort()
    {
        return $this->reuse_port;
    }

    /**
     * Generated from protobuf field <code>bool reuse_port = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setReusePort($var)
    {
        GPBUtil::checkBool($var);
        $this->reuse_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dns = 10;</code>
     * @return string
     */
    public function getDns()
    {
        return $this->dns;
    }

    /**
     * Generated from protobuf field <code>string dns = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDns($var)
    {
        GPBUtil::checkString($var, True);
        $this->dns = $var;

        return $this;
    }

}

