<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wireguard.proto

namespace Proto\Wireguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.wireguard.AddRequest</code>
 */
class AddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     */
    protected $device_name = '';
    /**
     * Generated from protobuf field <code>string interface_name = 3;</code>
     */
    protected $interface_name = '';
    /**
     * Generated from protobuf field <code>string public_key = 4;</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>string preshared_key = 5;</code>
     */
    protected $preshared_key = '';
    /**
     * Generated from protobuf field <code>string allowed_ips = 6;</code>
     */
    protected $allowed_ips = '';
    /**
     * Generated from protobuf field <code>string persistent_keepalive = 7;</code>
     */
    protected $persistent_keepalive = '';
    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     */
    protected $endpoint = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $device_name
     *     @type string $interface_name
     *     @type string $public_key
     *     @type string $preshared_key
     *     @type string $allowed_ips
     *     @type string $persistent_keepalive
     *     @type string $endpoint
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wireguard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string interface_name = 3;</code>
     * @return string
     */
    public function getInterfaceName()
    {
        return $this->interface_name;
    }

    /**
     * Generated from protobuf field <code>string interface_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInterfaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->interface_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key = 4;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string preshared_key = 5;</code>
     * @return string
     */
    public function getPresharedKey()
    {
        return $this->preshared_key;
    }

    /**
     * Generated from protobuf field <code>string preshared_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPresharedKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->preshared_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string allowed_ips = 6;</code>
     * @return string
     */
    public function getAllowedIps()
    {
        return $this->allowed_ips;
    }

    /**
     * Generated from protobuf field <code>string allowed_ips = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAllowedIps($var)
    {
        GPBUtil::checkString($var, True);
        $this->allowed_ips = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string persistent_keepalive = 7;</code>
     * @return string
     */
    public function getPersistentKeepalive()
    {
        return $this->persistent_keepalive;
    }

    /**
     * Generated from protobuf field <code>string persistent_keepalive = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPersistentKeepalive($var)
    {
        GPBUtil::checkString($var, True);
        $this->persistent_keepalive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

}

