<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wireguard.proto

namespace Proto\Wireguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.wireguard.DnsRequest</code>
 */
class DnsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     */
    protected $interface_name = '';
    /**
     * Generated from protobuf field <code>string dns = 2;</code>
     */
    protected $dns = '';
    /**
     * Generated from protobuf field <code>bool enable_dns = 3;</code>
     */
    protected $enable_dns = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $interface_name
     *     @type string $dns
     *     @type bool $enable_dns
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wireguard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     * @return string
     */
    public function getInterfaceName()
    {
        return $this->interface_name;
    }

    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInterfaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->interface_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dns = 2;</code>
     * @return string
     */
    public function getDns()
    {
        return $this->dns;
    }

    /**
     * Generated from protobuf field <code>string dns = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDns($var)
    {
        GPBUtil::checkString($var, True);
        $this->dns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_dns = 3;</code>
     * @return bool
     */
    public function getEnableDns()
    {
        return $this->enable_dns;
    }

    /**
     * Generated from protobuf field <code>bool enable_dns = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableDns($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_dns = $var;

        return $this;
    }

}

