<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wireguard.proto

namespace Proto\Wireguard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.wireguard.MountRequest</code>
 */
class MountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     */
    protected $interface_name = '';
    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     */
    protected $private_key = '';
    /**
     * Generated from protobuf field <code>string listen_port = 3;</code>
     */
    protected $listen_port = '';
    /**
     * Generated from protobuf field <code>string physical_interface = 4;</code>
     */
    protected $physical_interface = '';
    /**
     * Generated from protobuf field <code>string subnet = 5;</code>
     */
    protected $subnet = '';
    /**
     * Generated from protobuf field <code>string address = 6;</code>
     */
    protected $address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $interface_name
     *     @type string $private_key
     *     @type string $listen_port
     *     @type string $physical_interface
     *     @type string $subnet
     *     @type string $address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wireguard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     * @return string
     */
    public function getInterfaceName()
    {
        return $this->interface_name;
    }

    /**
     * Generated from protobuf field <code>string interface_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInterfaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->interface_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string listen_port = 3;</code>
     * @return string
     */
    public function getListenPort()
    {
        return $this->listen_port;
    }

    /**
     * Generated from protobuf field <code>string listen_port = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setListenPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->listen_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string physical_interface = 4;</code>
     * @return string
     */
    public function getPhysicalInterface()
    {
        return $this->physical_interface;
    }

    /**
     * Generated from protobuf field <code>string physical_interface = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhysicalInterface($var)
    {
        GPBUtil::checkString($var, True);
        $this->physical_interface = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subnet = 5;</code>
     * @return string
     */
    public function getSubnet()
    {
        return $this->subnet;
    }

    /**
     * Generated from protobuf field <code>string subnet = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSubnet($var)
    {
        GPBUtil::checkString($var, True);
        $this->subnet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

}

